# Generated by Django 4.0.3 on 2022-07-01 18:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilestore', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='uploads', max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
