# Generated by Django 4.0.3 on 2022-07-01 19:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilestore', '0004_products_color_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
